server:
  port: 9001

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://18.222.184.161:30001/minet1
    username: root
    password: Bootcamp@118!
    hikari:
      maximum-pool-size: 10
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    validate-on-migrate: false
  logging:
    level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
  config:
    import: optional:classpath:.env[.properties]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
