name: SonarCloud Backend
on:
  push:
    branches:
      - main # change it to your main branch.
      - branch-*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  user-service: # Change the job name to a backend microservice name.
    if: ( startsWith(github.head_ref, 'BE_') && ( github.event.pull_request.merged == false ) || ( github.event_name == 'push' ))
    name: BE user-service Sonar Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Give the value at most 8 mins.
    defaults:
      run:
        working-directory: backend/user-service # Change the working-directory to your microservice folder name.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of analysis.

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu" # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.USERSERVICE_TOKEN }} # Change the token name accordingly.
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=zemoso-int_bootcamp-be-118-user-service # Change the projectName and projectKey accordingly.

  portfolio-service: # Change the job name to a backend microservice name.
    if: ( startsWith(github.head_ref, 'BE_') && ( github.event.pull_request.merged == false ) || ( github.event_name == 'push' ))
    name: BE portfolio-service Sonar Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Give the value at most 8 mins.
    defaults:
      run:
        working-directory: backend/portfolio-service # Change the working-directory to your microservice folder name.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of analysis.

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu" # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.PORTFOLIO_SERVICE_TOKEN }} # Change the token name accordingly.
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=zemoso-int_bootcamp-be-118-portfolio-service # Change the projectName and projectKey accordingly.

  wallet-service: # Change the job name to a backend microservice name.
    if: ( startsWith(github.head_ref, 'BE_') && ( github.event.pull_request.merged == false ) || ( github.event_name == 'push' ))
    name: BE wallet-service Sonar Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Give the value at most 8 mins.
    defaults:
      run:
        working-directory: backend/wallet-service # Change the working-directory to your microservice folder name.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of analysis.

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu" # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.WALLET_SERVICE_TOKEN }} # Change the token name accordingly.
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=zemoso-int_bootcamp-be-118-wallet-service # Change the projectName and projectKey accordingly.

  crypto-service: # Change the job name to a backend microservice name.
    if: ( startsWith(github.head_ref, 'BE_') && ( github.event.pull_request.merged == false ) || ( github.event_name == 'push' ))
    name: BE crypto-service Sonar Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Give the value at most 8 mins.
    defaults:
      run:
        working-directory: backend/crypto-service # Change the working-directory to your microservice folder name.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of analysis.

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu" # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.CRYPTO_SERVICE_TOKEN }} # Change the token name accordingly.
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=zemoso-int_bootcamp-be-118-crypto-service # Change the projectName and projectKey accordingly.
